### ISSUE TITLE
On Windows check permissions of install/data folder during install or on launch

### ISSUE THREAD

**Issue by dma** [subgraph/Vega#105]
Build 108 and earlier - launch fails if user cannot write to default data directory. Observed on Window 7 Home and similar issue with Windows 8.

Exception (few like this) :

Caused by: java.lang.IllegalStateException: The platform metadata area could not be written: C:\Program Files (x86)\Vega\workspace.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
    at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
    at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:125)
    at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
    at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
    at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
    at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:392)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:380)
    at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
    at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
    at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
    at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
    at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
    at org.eclipse.core.runtime.preferences.InstanceScope.getNode(InstanceScope.java:80)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getStorePreferences(ScopedPreferenceStore.java:241)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.<init>(ScopedPreferenceStore.java:133)
    at org.eclipse.ui.plugin.AbstractUIPlugin.getPreferenceStore(AbstractUIPlugin.java:284)
    at com.subgraph.vega.application.Activator.start(Unknown Source)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    ... 34 more

**Comment by Bliksempie** [comment]
Running Vega as an administrator solves the problem for me. Hope it helps someone. 

Regards, 

Kobus.
