### ISSUE TITLE
Scanner script issue

### ISSUE THREAD

**Issue by giveen** [subgraph/Vega#118]
2:15:22 PM [WARNING](scanner) Wrapped exception running module script
Source file: x86)\Vega\scripts\scanner\modules\injection\local-file-include.js at line 13 and column 0
Wrapped java.lang.NullPointerException
    at com.subgraph.vega.impl.scanner.modules.scripting.ResponseJS.jsGet_fingerprint(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.ScriptableObject.getImpl(ScriptableObject.java:2020)
    at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:287)
    at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1437)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1423)
    at org.mozilla.javascript.gen.c18._c2(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js:13)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at org.mozilla.javascript.gen.c18._c6(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js:342)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at com.subgraph.vega.impl.scanner.modules.scripting.CrawlerCallbackWrapper.processResponse(Unknown Source)
    at com.subgraph.vega.impl.scanner.state.CrawlerCallbackWrapper.processResponse(Unknown Source)
    at com.subgraph.vega.internal.crawler.HttpResponseProcessor.runLoop(Unknown Source)
    at com.subgraph.vega.internal.crawler.HttpResponseProcessor.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by giveen** [comment]
2:15:48 PM [WARNING](scanner) Wrapped exception running module script
Source file: x86)\Vega\scripts\scanner\modules\injection\local-file-include.js at line 13 and column 0
Wrapped java.lang.NullPointerException
    at com.subgraph.vega.impl.scanner.modules.scripting.ResponseJS.jsGet_fingerprint(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.ScriptableObject.getImpl(ScriptableObject.java:2020)
    at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:287)
    at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:1617)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1437)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1423)
    at org.mozilla.javascript.gen.c18._c2(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js:13)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at org.mozilla.javascript.gen.c18._c6(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js:342)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c18.call(C:\Program Files (x86)\Vega\scripts\scanner\modules\injection\local-file-include.js)
    at com.subgraph.vega.impl.scanner.modules.scripting.CrawlerCallbackWrapper.processResponse(Unknown Source)
    at com.subgraph.vega.impl.scanner.state.CrawlerCallbackWrapper.processResponse(Unknown Source)
    at com.subgraph.vega.internal.crawler.HttpResponseProcessor.runLoop(Unknown Source)
    at com.subgraph.vega.internal.crawler.HttpResponseProcessor.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by dma** [comment]
Interesting error, we will investigate that. Thanks for the report.

**Comment by aarteagamolina** [comment]
Hello, any news about this bug? 
Cause of this I'm getting a Possible Local File Include vulnerability.
