### ISSUE TITLE
vega subgraph get this erorr on kali sna 

### ISSUE THREAD

**Issue by hcstorm** [subgraph/Vega#123]
HI  all 
when i want to open vega on kali linux  it is get  ( canot open workspace) and when i try to open it from terminal it get this errors :
root@kali:~# vega
com.db4o.ext.DatabaseMaximumSizeReachedException
    at com.db4o.internal.LocalObjectContainer.checkBlockedAddress(LocalObjectContainer.java:328)
    at com.db4o.internal.LocalObjectContainer.appendBytes(LocalObjectContainer.java:316)
    at com.db4o.internal.ids.InMemoryIdSystem.allocateSlot(InMemoryIdSystem.java:97)
    at com.db4o.internal.ids.InMemoryIdSystem.commit(InMemoryIdSystem.java:63)
    at com.db4o.internal.ids.TransactionalIdSystemImpl.commit(TransactionalIdSystemImpl.java:59)
    at com.db4o.internal.ids.BTreeIdSystem.commit(BTreeIdSystem.java:162)
    at com.db4o.internal.ids.TransactionalIdSystemImpl.commit(TransactionalIdSystemImpl.java:59)
    at com.db4o.internal.ids.BTreeIdSystem.commit(BTreeIdSystem.java:162)
    at com.db4o.internal.ids.TransactionalIdSystemImpl.commit(TransactionalIdSystemImpl.java:59)
    at com.db4o.internal.LocalTransaction.commitImpl(LocalTransaction.java:130)
    at com.db4o.internal.LocalTransaction.commit(LocalTransaction.java:69)
    at com.db4o.internal.LocalTransaction.commit(LocalTransaction.java:59)
    at com.db4o.internal.ObjectContainerBase.initializePostOpenExcludingTransportObjectContainer(ObjectContainerBase.java:1143)
    at com.db4o.internal.ObjectContainerBase.initializePostOpen(ObjectContainerBase.java:1132)
    at com.db4o.internal.ObjectContainerBase.access$200(ObjectContainerBase.java:38)
    at com.db4o.internal.ObjectContainerBase$1.run(ObjectContainerBase.java:141)
    at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
    at com.db4o.foundation.Environments.runWith(Environments.java:28)
    at com.db4o.internal.ObjectContainerBase.withEnvironment(ObjectContainerBase.java:161)
    at com.db4o.internal.ObjectContainerBase.open(ObjectContainerBase.java:131)
    at com.db4o.internal.IoAdaptedObjectContainer.<init>(IoAdaptedObjectContainer.java:35)
    at com.db4o.internal.ObjectContainerFactory.openObjectContainer(ObjectContainerFactory.java:18)
    at com.db4o.Db4oEmbedded.openFile(Db4oEmbedded.java:65)
    at com.subgraph.vega.internal.model.DatabaseConfigurationFactory.openContainer(Unknown Source)
    at com.subgraph.vega.internal.model.Workspace.openDatabase(Unknown Source)
    at com.subgraph.vega.internal.model.Workspace.open(Unknown Source)
    at com.subgraph.vega.internal.model.Model.openWorkspaceEntry(Unknown Source)
    at com.subgraph.vega.internal.model.Model.openDefaultWorkspace(Unknown Source)
    at com.subgraph.vega.application.Application.setupWorkspace(Unknown Source)
    at com.subgraph.vega.application.Application.start(Unknown Source)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

---

any solution for this erorr

**Comment by dma** [comment]
Hi hcstorm, have you tried to move the model.db file to a backup location? Try that, and then re-start Vega.

**Comment by hcstorm** [comment]
thank you sir 
it is ok thank you again
