### ISSUE TITLE
Vega crashes on Linux

### ISSUE THREAD

**Issue by nan008** [subgraph/Vega#140]
I am trying to open Vega on Centos 7

getting error:

```bash

SESSION 2017-05-30 11:03:29.644 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2017-05-30 11:03:32.746
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4387)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:913)
	at org.eclipse.swt.widgets.Display.create(Display.java:899)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:156)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:497)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:488)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:716)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:161)
	at com.subgraph.vega.application.Application.start(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

have those installed

Installed Packages
gtk2.x86_64                                                       2.24.28-8.el7                                                 @base
gtk2-devel.x86_64                                            2.24.28-8.el7                                                 @base
gtk3.x86_64                                                       3.14.13-20.el7_3.1                                          @updates

**Comment by shubhamjain0127** [comment]
Hi were you able to solve the above issue.? I am getting the same issue while installing Vega on Centos 7
