### ISSUE TITLE
have problem open VEGA on my Kali linux after i install

### ISSUE THREAD

**Issue by championkali** [subgraph/Vega#156]
I have finish  zipping it and this is the error it give me when i want to open. can someone help me please
An error has occurred. See the log file
/root/Desktop/vega/configuration/1525853085083.log.

**Comment by drastiK91** [comment]
provide the log,
if the error comes up after an upgrade of your deps, probably you have to change your default java version
run "sudo update-alternatives --config java"
and choose java 8 if available

thats works for me but without the log solve your problem is like a shot when you are blind :)

**Comment by championkali** [comment]
Yes the method you show me has work
Thank you

**Comment by chrysos-ll** [comment]
it's work for me too, thank you

**Comment by kravchenko21456** [comment]
Not working

**Comment by drastiK91** [comment]
paste your log man i will try to help

**Comment by mrafshin** [comment]
thank you it's work 👍

**Comment by prasanthnakka** [comment]
!SESSION 2018-07-07 15:51:01.704 -----------------------------------------------
eclipse.buildId=unknown
java.version=10.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2018-07-07 15:51:03.806
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: The bundle "org.eclipse.equinox.simpleconfigurator_1.0.300.v20110815-1744 [1]" could not be resolved. Reason: Missing Constraint: Bundle-RequiredExecutionEnvironment: CDC-1.1/Foundation-1.1,J2SE-1.4
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1177)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.osgi 4 0 2018-07-07 15:51:03.822
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.equinox.simpleconfigurator_1.0.300.v20110815-1744.jar was not resolved.

!ENTRY org.eclipse.osgi 2 0 2018-07-07 15:51:03.859
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2018-07-07 15:51:03.859
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.equinox.simpleconfigurator_1.0.300.v20110815-1744.jar was not resolved.
!SUBENTRY 2 org.eclipse.equinox.simpleconfigurator 2 0 2018-07-07 15:51:03.859
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(|(&(osgi.ee=CDC/Foundation)(version=1.1))(&(osgi.ee=JavaSE)(version=1.4)))".

!ENTRY org.eclipse.osgi 2 0 2018-07-07 15:51:03.867
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2018-07-07 15:51:03.867
!MESSAGE Bundle org.eclipse.equinox.simpleconfigurator_1.0.300.v20110815-1744 [1] was not resolved.
!SUBENTRY 2 org.eclipse.equinox.simpleconfigurator 2 0 2018-07-07 15:51:03.868
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(|(&(osgi.ee=CDC/Foundation)(version=1.1))(&(osgi.ee=JavaSE)(version=1.4)))".

!ENTRY org.eclipse.osgi 4 0 2018-07-07 15:51:03.886
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:74)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by pooya-ahmady** [comment]
thanks

**Comment by aslisubhash** [comment]
Worked for me

**Comment by 0xrisec** [comment]
It's work .thank you :)

**Comment by pakitowicz** [comment]
Hey prasanthnakka and @championkali  I had the same problem when I tried to run it as user. I tried java fix stated above and nothing helped. It turned out that when I run vega as sudo then I had no issues. Try:
`sudo vega` 
That should work. If not try to run:
`sudo apt-get install vega` and then `sudo vega`
You should be able to run it with root privilages.

**Comment by babuhacker** [comment]
Send happened to me.

**Comment by 0xrisec** [comment]
Same happened to me😀

**Comment by sandymanner** [comment]
OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.internal.baseadaptor.BaseStorage (file:/usr/share/vega/plugins/org.eclipse.osgi_3.8.0.v20120529-1548.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.baseadaptor.BaseStorage
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by sandymanner** [comment]
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)
java version which I have !

**Comment by sandymanner** [comment]
It started working with this command "
sudo update-alternatives --config java"
Kali Linux

**Comment by NMR87** [comment]
This didn't helped for me in Kali 2018. I changed the RE version to 8 and a new error appears. 

"org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]"

my research results about this errortype is the missing "libwebkitgtk-1.0".  but apt-get install libwebkitgtk-1.0 isn't available anymore. so I installed (all) libwebkit2gtk. But I still get the same error-message: 

"An error has occurred. See the log file
/root/Downloads/VegaBuild-linux.gtk.x86_64/vega/workspace/.metadata/.log."

When i opened the long logfile i get on the top the message above.

I hope some of you guys can help me :-)

**Comment by infosecwatchman** [comment]
I've tried the update-alternatives, but like @NMR87 it produced a different error.

**Comment by NMR87** [comment]
@AltF4bulous I found a solution after hours and hours of trying. It took a lot of time but it is easier as I expected:

Add to yout source list in kali linux the original debian sourcelist from 
https://wiki.debian.org/SourcesList

After that you run apt-get update 
now you can find apt-get install libwebkitgtk-1.0

After the installation I removed the debian sources from my kali list and rund apt-get clean. 

Now you can enjoy vega :)

**Comment by IsaiasWalton** [comment]
> 
> 
> @AltF4bulous I found a solution after hours and hours of trying. It took a lot of time but it is easier as I expected:
> 
> Add to yout source list in kali linux the original debian sourcelist from
> https://wiki.debian.org/SourcesList
> 
> After that you run apt-get update
> now you can find apt-get install libwebkitgtk-1.0
> 
> After the installation I removed the debian sources from my kali list and rund apt-get clean.
> 
> Now you can enjoy vega :)

Thank you a lot dude for your efforts and sharing with us !!! YOU ROCK ;)
This method is working for people who had the error even if you have changed to Java 8 !

**Comment by noraj** [comment]
#159 #160

**Comment by rahulreddyayyapaneni** [comment]
> @AltF4bulous I found a solution after hours and hours of trying. It took a lot of time but it is easier as I expected:
> 
> Add to yout source list in kali linux the original debian sourcelist from
> https://wiki.debian.org/SourcesList
> 
> After that you run apt-get update
> now you can find apt-get install libwebkitgtk-1.0
> 
> After the installation I removed the debian sources from my kali list and rund apt-get clean.
> 
> Now you can enjoy vega :)

I am actually not aware about adding source list. Can you or someone explain in details or provide me any source of information. @NMR87 @IsaiasWalton

**Comment by havang1412** [comment]
@AltF4bulous,great, it worked.
thanks a lot

**Comment by havang1412** [comment]
@All, who are getting this issue, please follow the steps to fix it
1. download vega from subgraph.com (store it at Downloads folder on Kali)
2. at this source into the sources.list: deb http://ftp.debian.org/debian stable main contrib non-free
then apt-get update and apt-get install libwebkitgtk-1.0, then remove debian source from yr kali and run apt-get clean
3. enjoy vega with the following command: root@kali:~/Downloads/VegaBuild-linux.gtk.x86_64/vega#./Vega

**Comment by hackersden09** [comment]
> provide the log,
> if the error comes up after an upgrade of your deps, probably you have to change your default java version
> run "sudo update-alternatives --config java"
> and choose java 8 if available
> 
> thats works for me but without the log solve your problem is like a shot when you are blind :)

An error has occurred. See the log file
/root/Desktop/vega/workspace/.metadata/.log.

**Comment by alca1398** [comment]
An error has occurred. See the log file
/root/workspace/.metadata/.log.
:(

**Comment by Virussssss** [comment]
E: Unable to locate package https://github.com/vega
E: Couldn't find any package by glob 'https://github.com/vega'
E: Couldn't find any package by regex 'https://github.com/vega'


i cant install vega please help me

**Comment by hamedGOS** [comment]
how to install vega in kali linux and fix all errors

https://www.youtube.com/watch?v=E5WePDXTdng

**Comment by ghost** [comment]
@Virussssss I recommend installing it from the vega website and extracting the folder somewhere, then running it.

@alca1398 @hackersden09  Unless you post the relevant part of the logs, we cannot help you. However, I would guess that your problem is that you don't have the old libwebkitgtk-1.0-0 library installed. Vega web scanner uses this old one instead of the new one.

To fix this issue:
1. Open your apt sources list:
nano /etc/apt/sources.list

2. Add this entry to it, then save:
deb http://deb.debian.org/debian oldstable main non-free contrib

3. Update your apt-cache:
apt-get update

4. Install libwebkitgtk-1.0-0:
apt-get install libwebkitgtk-1.0-0 

5. Try running Vega again

**Comment by borhanDZ** [comment]
@NMR87 thank you a lot it work for me

**Comment by lmh122** [comment]
thank you

**Comment by sysdefendr** [comment]
> 
> 
> @Virussssss I recommend installing it from the vega website and extracting the folder somewhere, then running it.
> 
> @alca1398 @hackersden09 Unless you post the relevant part of the logs, we cannot help you. However, I would guess that your problem is that you don't have the old libwebkitgtk-1.0-0 library installed. Vega web scanner uses this old one instead of the new one.
> 
> To fix this issue:
> 
>     1. Open your apt sources list:
>        nano /etc/apt/sources.list
> 
>     2. Add this entry to it, then save:
>        deb http://deb.debian.org/debian oldstable main non-free contrib
> 
>     3. Update your apt-cache:
>        apt-get update
> 
>     4. Install libwebkitgtk-1.0-0:
>        apt-get install libwebkitgtk-1.0-0
> 
>     5. Try running Vega again

You're a hero. Many thanks.

**Comment by ezzio-salas** [comment]
> > @Virussssss I recommend installing it from the vega website and extracting the folder somewhere, then running it.
> > @alca1398 @hackersden09 Unless you post the relevant part of the logs, we cannot help you. However, I would guess that your problem is that you don't have the old libwebkitgtk-1.0-0 library installed. Vega web scanner uses this old one instead of the new one.
> > To fix this issue:
> > ```
> > 1. Open your apt sources list:
> >    nano /etc/apt/sources.list
> > 
> > 2. Add this entry to it, then save:
> >    deb http://deb.debian.org/debian oldstable main non-free contrib
> > 
> > 3. Update your apt-cache:
> >    apt-get update
> > 
> > 4. Install libwebkitgtk-1.0-0:
> >    apt-get install libwebkitgtk-1.0-0
> > 
> > 5. Try running Vega again
> > ```
> 
> You're a hero. Many thanks.

You are also my Hero

**Comment by Ma5t3rful** [comment]
Hello guys I'm a Manjaro user. when I paste this command into the terminal it says:
"sudo update-alternatives --config java"
sudo: update-alternatives: command not found

**Comment by anneborcherding** [comment]
> Hello guys I'm a Manjaro user. when I paste this command into the terminal it says:
> "sudo update-alternatives --config java"
> sudo: update-alternatives: command not found

`update-alternatives` does not work on Manjaro, I think you could follow the steps shown [here](https://medium.com/@petehouston/switch-java-versions-on-any-systems-you-like-f0c996b4f57a)

**Comment by akfrey171** [comment]
Is this error because of the wrong Java format?

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Gtk-Message: 14:11:25.988: Failed to load module "gail"

** (Vega:2135376): WARNING **: 14:11:25.995: (../atk-adaptor/bridge.c:1018):atk_bridge_adaptor_init: runtime check failed: (root)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.internal.baseadaptor.BaseStorage (file:/usr/share/vega/plugins/org.eclipse.osgi_3.8.0.v20120529-1548.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.baseadaptor.BaseStorage
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Gtk-Message: 14:11:26.300: Failed to load module "gail"

** (Vega:2135375): WARNING **: 14:11:26.307: (../atk-adaptor/bridge.c:1018):atk_bridge_adaptor_init: runtime check failed: (root)

**Comment by samoMM** [comment]
An error has occurred. See the log file
/home/kali/.eclipse/com.subgraph.vega.application.product_1.0.0.201410142137_835378376/configuration/1687243794739.log.

**Comment by Alex2024-thebestcoder** [comment]
> An error has occurred. See the log file /home/kali/.eclipse/com.subgraph.vega.application.product_1.0.0.201410142137_835378376/configuration/1687243794739.log.

have you found the solution ? because i have been looking for it everywhere , but all in vain

**Comment by akfrey171** [comment]
Bro, I'm still using Windows that's how much I haven't fixed it. I think
it's gone..
I let the system updates go too long and there ain't no coming back I'm
sorry to say.
I hope you have better luck

**Comment by Divixilixi** [comment]
i'm using it on Windows 11 can any one help
