### ISSUE TITLE
Proxy PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID exception

### ISSUE THREAD

**Issue by dma** [subgraph/Vega#16]
Using Vega proxy to access HTTPS site. It was working but suddenly it started failing with this exception.

8:59:08 AM [WARNING](proxy) IOException processing client request in proxy
javax.net.ssl.SSLException: java.security.ProviderException: sun.security.pkcs11.wrapper.8:59:08 AM [WARNING](proxy) IOException processing client request in proxy
javax.net.ssl.SSLException: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1868)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1826)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1809)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1328)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1305)
    at com.subgraph.vega.internal.http.proxy.VegaHttpService.handleConnect(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.VegaHttpService.handleRequest(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.ConnectionTask.processingLoop(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.ConnectionTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
    at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:323)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:687)
    at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:63)
    at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1204)
    at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1058)
    at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:887)
    at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:620)
    at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:167)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:998)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1294)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1321)
    ... 8 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
    at sun.security.pkcs11.wrapper.PKCS11.C_GenerateKeyPair(Native Method)
    at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:314)
    ... 20 more
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1868)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1826)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1809)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1328)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1305)
    at com.subgraph.vega.internal.http.proxy.VegaHttpService.handleConnect(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.VegaHttpService.handleRequest(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.ConnectionTask.processingLoop(Unknown Source)
    at com.subgraph.vega.internal.http.proxy.ConnectionTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
    at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:323)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:687)
    at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:63)
    at sun.security.ssl.ServerHandshaker.setupEphemeralECDHKeys(ServerHandshaker.java:1204)
    at sun.security.ssl.ServerHandshaker.trySetCipherSuite(ServerHandshaker.java:1058)
    at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:887)
    at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:620)
    at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:167)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:998)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1294)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1321)
    ... 8 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_DOMAIN_PARAMS_INVALID
    at sun.security.pkcs11.wrapper.PKCS11.C_GenerateKeyPair(Native Method)
    at sun.security.pkcs11.P11KeyPairGenerator.generateKeyPair(P11KeyPairGenerator.java:314)
    ... 20 more

**Comment by zeyuanpinghe** [comment]
ARE you solved it ?
And I encountered it  too.
